#项目名称
spring:
  application:
    name: community-service-web

# 数据源配置
  datasource:

    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

#  mybatis
  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mapper/*.xml